# Generated by Django 4.0 on 2023-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(max_length=50, null=True)),
                ('about_work', models.CharField(max_length=50, null=True)),
                ('suggestions', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('profile_photo', models.FileField(null=True, upload_to='documents /')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddMaterialUsages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_location', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('uom', models.CharField(max_length=50, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('usage_date', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('tender_type', models.CharField(max_length=50, null=True)),
                ('total_budget', models.CharField(max_length=50, null=True)),
                ('end_date', models.DateField(null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTenderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=50, null=True)),
                ('contractor_id', models.CharField(max_length=50, null=True)),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTenderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(max_length=50, null=True)),
                ('tender_id', models.CharField(max_length=50, null=True)),
                ('work_per', models.IntegerField(null=True)),
                ('upload_photo', models.FileField(null=True, upload_to='documents/')),
                ('entry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('paid_date', models.DateField(null=True)),
                ('tender_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('utype', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
