# Generated by Django 4.0 on 2023-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtpCode',
            new_name='OtpCodeNew',
        ),
    ]
