# Generated by Django 4.0 on 2023-11-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contractor_delete_addcontractor_delete_tenderpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddContractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('profile_photo', models.FileField(null=True, upload_to='documents')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
