# Generated by Django 4.0 on 2023-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addcontractors_delete_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtender',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
