# Generated by Django 4.0 on 2023-11-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_addtender_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='status',
        ),
    ]
