# Generated by Django 4.0 on 2023-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_userlogin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('tender_type', models.CharField(max_length=50, null=True)),
                ('total_budget', models.CharField(max_length=50, null=True)),
                ('starting_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddTender',
        ),
    ]
