# Generated by Django 4.0 on 2023-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_addtenders_delete_addtender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(max_length=50, null=True)),
                ('tender_id', models.CharField(max_length=50, null=True)),
                ('work_per', models.IntegerField(null=True)),
                ('entry_date', models.DateField(null=True)),
                ('upload_photo', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='AddTenderProgress',
        ),
    ]
