# Generated by Django 4.0 on 2023-11-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tenderprogress_delete_addtenderprogress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenderProgress',
            new_name='NewTenderProgress',
        ),
    ]
