# Generated by Django 4.0 on 2023-12-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_tenderprogress_newtenderprogress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddTenders',
            new_name='AddTender',
        ),
    ]
